version: 0.0
os: linux
files:
  - source: /
    destination: /root/app
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root