services:
  api-server:
    image: inflpick/api-server:latest
    restart: always
    container_name: api-server
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
    networks:
      inflpick:
        ipv4_address: 172.10.0.1
networks:
  inflpick:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.32.128