services:
  api-server:
    image: inflpick/api-server:latest
    restart: always
    container_name: api-server
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}