spring:
  data:
    mongodb:
      uri: ENC(itRW/kbSl2zOGsmE86hBYUG+Kw8LA56tIyxH3pDfa0Na+rB37pdpE1u2iE2rVVdgIwpbc0YOAEWPVx8z4W1NW8aAP6ol194aUVL2gPWRpaTdcPOj7V9atPjWRC5KcRGD4aeAJETXjIswGUSqyew2e9s6uUSfpHlWoxMex1e9bus=)
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ENC(LYCG6lhGqfApl5/VQnBD6NI1GXEzHCyCphKt99CLTDX3h8qn1vgvy9C+AR7qyX/LoJ1DYZVD9ueBe9IXiAJUeQ==)
          naver:
            redirect-uri: ENC(2H48aVH4kVoAVAHGbscNFiPSPXohiygPYeOFIIKGm520Vadx4x9RoZ+1SF7ZdZ/KCGuteKapKPAf+z7vxOkkCA==)
          kakao:
            redirect-uri: ENC(ODQ26qefQwGoBYFPqNrINJflh37/WVhGy3U3mT8uUhAMo6jMl/K9/wzVRFDyNcIzuSaMj56wmJTzSuvkBApvuQ==)
logging:
  level: # 적용할 곳과 레벨을 지정합니다.
    root: error
    com.leesh: warn
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD} # 암호화 키를 지정합니다.
custom:
  storage:
    uri:
      scheme: https
      host: cdn.inflpick.com
      base-path: 'data'
    aws:
      s3:
        region: ap-northeast-2
        bucket-name: api-server-data
  cors:
    allowed-origin-patterns:
      - 'https://inflpick.com'
      - 'https://api.inflpick.com'
  cookie:
    same-site: 'None' # Strict, Lax, None 중 하나를 선택합니다. None 이면, Secure 속성이 필요합니다.
    redirect-uri: 'https://inflpick.com/oauth2/success' # 요청을 리다이렉트할 경로를 지정합니다.
    domain: 'inflpick.com' # 쿠키를 전송할 도메인을 지정합니다.
    secure: true # HTTPS 에서만 쿠키 전송
