spring:
  application:
    name: api-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/api-server
springdoc:
  swagger-ui:
    path: /api-docs.html # Web UI 접속 경로
    default-models-expand-depth: -1 # API 문서 밑에 Schema 모델 없애기
  api-docs:
    path: /v3/api-docs # OpenAPI 접속 경로
