spring:
  application:
    name: api-server
  data:
    mongodb:
      uri: mongodb://myuser:mypassword@localhost:27017/api-server
springdoc:
  swagger-ui:
    default-models-expand-depth: -1 # API 문서 밑에 Schema 모델 없애기
    enabled: true
    path: /swagger-ui.html  # Swagger UI 기본 접속 경로
  api-docs:
    enabled: true
    path: /v3/api-docs # Swagger API 기본접속 경로
logging:
  level: # 적용할 곳과 레벨을 지정합니다.
    root: warn
    com.leesh: debug
  file: # 로그 파일에 대한 명시입니다. 주의점 name과 path중 하나만 사용해야합니다. path 사용을 권장합니다.
    path: logs # 로그 파일의 위치 절대 경로를 적어주시면 됩니다.
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/${spring.application.name}.%d{yyyy-MM-dd_HH-mm-ss}.log
      clean-history-on-start: false # 애플리케이션 재실행시 로그 파일을 초기화 여부 설정
      max-file-size: 5MB # 로그 파일의 최대 크기이며, 크기가 넘어가면 새로운 로그파일 작성
      max-history: 30 # 로그 파일의 최대 수
      total-size-cap: 50MB # 로그 파일의 총 크기이며, 넘어갈 시 가장 오래된 로그 파일 삭제
