name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches
      - '#15-cicd' # Temporary branches

permissions:
  contents: read
  id-token: write # aws-actions/configure-aws-credentials@v4 사용 시 필요

env:
  APP_NAME: 'api-server'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
#      - name: 'Set up JDK 21'
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'corretto'
#      - name: 'Qodana Scan'
#        uses: JetBrains/qodana-action@v2024.1.9
#        with:
#          pr-mode: false
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1109214742 }}
#          QODANA_ENDPOINT: 'https://qodana.cloud'
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Lists the files in the repository'
        run: ls -al
      - name: 'Build and push Docker images'
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: /infra/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_NAMESPACE }}/api-server:latest


