name: '코드 품질 검사'

on:
  pull_request:
    types:
      - opened # PR이 열렸을 때
      - synchronize # PR이 업데이트 되었을 때
      - reopened # PR이 다시 열렸을 때

jobs:
  run-on-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write # 콘텐츠를 읽고 쓸 수 있는 권한
      pull-requests: write # PR을 읽고 쓸 수 있는 권한
      checks: write # 체크 실행을 위한 권한
    steps:
      - name: 'Git checkout' # Git 체크아웃
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ github.event.pull_request.head.sha }} # 실제 PR 커밋을 체크아웃 (머지 커밋이 아님)
          fetch-depth: 0 # PR 분석을 위해 전체 기록을 가져옴
#      - name: 'Qodana Scan' # Qodana 코드 품질 스캔 수행
#        uses: JetBrains/qodana-action@v2024.1.9
#        with:
#          pr-mode: true # PR 모드 활성화
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1109214742 }} # Qodana 인증 토큰
#          QODANA_ENDPOINT: 'https://qodana.cloud' # Qodana 엔드포인트
